packages:
  - app1/
  - app2/

catalog:
  concurrently: ^8.2.2
  external-remotes-plugin: ^1.0.0

catalogs:
  react18:
    react: "^18.2.0"
    react-dom: "^18.2.0"

  babel:
    "@babel/core": "^7.23.0"
    "@babel/preset-react": "^7.22.0"
    babel-loader: "^9.1.0"

  webpack5:
    webpack: "^5.89.0"
    webpack-cli: "^5.1.0"
    webpack-dev-server: "^4.15.0"
    html-webpack-plugin: "^5.5.0"

  zephyr:
    zephyr-webpack-plugin: "^0.0.56"
